title: John Fernkas
description: Software engineer and maker.
url: "https://johnfernkas.com"
baseurl: ""

permalink: /:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.pdf"
